### PR TITLE
create tests to match with other libs

### PR DESCRIPTION
**Pull request by marco-carvalho**

### CODE REVIEW

**Comment by ai** [comment]
Can you explain a reasons behind this PR?

**Comment by marco-carvalho** [comment]
correct me if i'm wrong, but i was thinking that one of the main concerns of this project was to be able to easily replace others libs that are worse in terms of size/speed, and this tests checks it

**Comment by ai** [comment]
1. The simple case will not show compatibility issues. All color libraries add single color in the same way. You need more complex issues to find a problem.
2. All libraries does complex examples in a different way. There is no way to be 100% compatible with them because they are not compatible to each other.

**Comment by marco-carvalho** [comment]
you're right, this PR doesn't check it 100%, but i was thinking that it kinda helps 😄 but feel free to close it if doesn't make sense

**Comment by ai** [comment]
Yeap. The difference will be on `red('a ' + green('b') + ' c')` vs `chalk.red('a ' + chalk.green('b') + ' c')`.

Chalk reset the color (from green) and then switch it back to red. Nano Colors just switch green to red.

I am not sure that we need to change it.

**Pull request closed without merging**
