### PR TITLE
<3

### PR DESCRIPTION
**Pull request by corysimmons**

### CODE REVIEW

**Comment by corysimmons** [comment]
@jorgebucaran does this solve your issue? I love you both btw.

**Comment by ai** [comment]
The origin text and position was already discussed with @jorgebucaran

**Comment by jorgebucaran** [comment]
Thank you, @corysimmons! 😄 

> ...does this solve your issue? 

Unfortunately, it does not. Because that's not what this is. This is an identical copy. Same API. Same types. Same implementation. Same performance. Different name. This message creates the illusion that nanocolors is fundamentally distinct, when it is not. It only adds to the confusion. As an external observer, I'd probably even believe the owner of this repository was a true OSS champion!

Colorette isn't some obscure project either. It is well used. Now imagine I find a project that meets that description. Clone it. Erase the `.git` directory. Initialize a new repository. Make a few extraneous changes. Incorrectly benchmark it ([see realistic results here](https://github.com/jorgebucaran/color-bench-test)). Falsely claim improved performance. Tweak the docs. Change the name. Add a logo. Start aggressively promoting it and sending PRs to high-profile projects while leveraging a non-trivial social media following (https://github.com/babel/babel/pull/13783, https://github.com/eslint/eslint/pull/15102).  

I have to believe he knows what he is doing, so I had to [call him out](https://twitter.com/jorgebucaran/status/1441713235980275718) on his behavior. 

The vast majority of the people that have come here and seen this repository or started using it as a dependency on their projects, either ignore the existence of Colorette, which is all right, or believe that nanocolors must be somewhat different. Hopefully a lot better. It must be, right? Why would it exist otherwise? My point exactly. It _isn't_. nanocolors adds strictly and technically zero new value. This situation is so absurd, that I myself would find it hard to believe in the first place. 

I'm not against forking a project and adding new value to it. I encourage that. But that's not what's going on here. This is the [collector](https://marvelcinematicuniverse.fandom.com/wiki/Collector) getting away with a new piece for their collection.

What getting away with your way looks like!

Imagine someone did exactly that to a very high-profile project like Babel or React. No one will pay the slightest attention. Why would they? I'd probably check the calendar to make sure it's not April Fools. Imagine a notable authority in the OSS community did that to a smaller, or perhaps not as well-recognized project. Now, that must be something. That's exactly what happened here.

**Comment by ai** [comment]
Here is a full list of changes in Nano Colors: https://github.com/ai/nanocolors/wiki/Colorette-Changes

Calling it as “rebranding” is a lie.

**Comment by jorgebucaran** [comment]
With your most recent patch, you introduced breaking changes. One has to explicitly cast numbers and dates now, which are not uncommon. That's a bug. Printing `undefined` is odd too. 🤷‍♂️

You get significantly more op/s because you are not handling several edge cases. Sounds irresponsible to me that you possibly broke your [13K+](https://github.com/ai/nanocolors/network/dependents?package_id=UGFja2FnZS0yNzI0MDQ2MTkx) dependants to score better in the test.

We're no longer comparing apples to apples. If you are not going to fix that, how can the benchmark be considered accurate? AFAIC chalk, kleur, ansi-colors, all correctly colorize numbers, and dates, and even `null` and `Infinity`.

**Comment by ai** [comment]
> With your most recent patch, you introduced breaking changes.

What is breaking changes in 0.2.6?

**Comment by jorgebucaran** [comment]
Coloring `undefined` is odd, but you fixed it. Well done. 👍

**Comment by jorgebucaran** [comment]
Coloring `undefined` is odd, but you fixed everything else. Well done. 👍

**Comment by johnnyshields** [comment]
@ai, @jorgebucaran has been maintaining this color library for nearly a decade of his life. You've created a fork in the last 22 hours and are now adding it as a dependency to some of the most widely used JS libs in existence. If you like Jorge's work, the best way would be to promote his lib for these repos and submit patches to him as needed. It would be great if you can use your influence to elevate others in the community instead of effectively stealing their work.

**Comment by ai** [comment]
@johnnyshields please read this thread https://mobile.twitter.com/sitnikcode/status/1441824191624486924

I promote Colorette for a year and send PRs to the project. I forget Colorette for a reason (API changes in 2.x and refuse the changes, API breaking changes in patch release).

Also Colorette author backported my performance improvements and refuse to mention me.

**Comment by johnnyshields** [comment]
@ai you raise good points around API stability and release versioning. Do you think perhaps @jorgebucaran could take this as a learning experience and you both might find a way to move forward here? I know Jorge personally and he is a sharp guy who has been in this space for a long time. It would make sense to assume he acted with good intentions.

**Comment by ai** [comment]
@johnnyshields I do not know @jorgebucaran in person, maybe you can help me. Here are a few facts, why worry me a lot. Maybe you can explain it to me?

1. Yesterday, I found a new way of making ANSI color libraries become 2x time faster. @jorgebucaran copied this idea, but when I ask him to mention Nano Colors, [he refuse](https://github.com/jorgebucaran/colorette/issues/78) and even made a very strange `!x ? A : B` → `x ? B : A` change. It shows me that he didn’t have good intentions, but maybe I am wrong?
2. Kleur community [tells](https://twitter.com/slightlycode/status/1442026694097793030) that we have a system problem of copying other ideas. He is very active on asking others to mention him, but do not listen to others when they ask him to mention his inspirations.

If he is a good person, why he refuse to mention me after he copied my performance optimization? And why other communities hates him to coping their work?

**Comment by jorgebucaran** [comment]
Colorette, previously known by other names predates [kleur](https://github.com/lukeed/kleur/commit/a9041634f44ef35cecbad8aaa2af28abf908ae54) by 2 or 3 years. It was introduced [here](https://github.com/jorgebucaran/colorette/tree/214efe5a698a937baa5e559250264cb0e12d3076) (2015). 🤦‍♂️ 

---

I'd like to remind you that I never refused to do anything. I was not given an option. I'd also like to point out that I reached out to Andrey first. I sought to work together on this. I said I was willing to help in any capacity, but he said it was too late. 

Here's the thing, he stripped my `git` history, and didn't attribute me. When I confronted him in private he made concessions, like, saying that nanocolors was inspired by Colorette (which was still incorrect as an identical copy is not a derivative work). 

When I called him out on Twitter he admitted to adding a COPYRIGHT file, retroactively included my `git` history in this repository, and mentioned nanocolors is actually a fork of Colorette. 👍 

Why did I call him out? Because he had aggressively begun to promote nanocolors as his own concoction and send PRs to high-profile projects to switch to it after having just published it. [He never described it as a fork of Colorette or said it was his inspiration](https://github.com/babel/babel/pull/13783#issue-1005077678) anywhere.

So, why is the flame still burning? Beats me. I thought we were done by yesterday, but Andrey is resolute to double-down on this until he completely self-destructs. 

---

Hey, @johnnyshields, long time no see! I'm still processing what happened, but I definitely learned a lot from this experience.

As for a way to move forward (https://github.com/babel/babel/pull/13783#issuecomment-927258580):
> I'm willing to put our differences behind us. The community doesn't really need two practically identical packages that accomplish the same thing. I'd be happy to add you as a Colorette maintainer and shake hands on this. How about we work together instead?

**Comment by ai** [comment]
@jorgebucaran it doesn’t explain why you are still refuse to mention Nano Colors after your back-ported it optimizations.

Now the story turned upside-down.

**Comment by johnnyshields** [comment]
> it doesn’t explain why you are still refuse to mention Nano Colors after your back-ported it optimizations.

@ai when you play this sort of silly game it completely destroys your credibility. You did a few minor changes that you could have easily raised as a PR directly to colorette. Meanwhile you took @jorgebucaran's entire original work without attribution, until you were publicly called out on it. Let's keep the discussion focused on real solutions.

**Comment by ai** [comment]
> @ai when you play this sort of silly game it completely destroys your credibility. You did a few minor changes that you could have easily raised as a PR directly to colorette.

I send PRs to coloretter before. I stopped to do it when @jorgebucaran break API in 2.x and refused ti change it back. Why it is not a good reason to create a fork, when author do not want old API to be returned?

> Meanwhile you took @jorgebucaran's entire original work without attribution, until you were publicly called out on it. Let's keep the discussion focused on real solutions.

He is mentioned in `COPYRIGHT`, he is mentioned in docs, the whole project history is in place? What fork rules did I violated  for now?

**Comment by johnnyshields** [comment]
@ai in babel/babel#13783 Jorge is offering to make you a colorette maintainer and its seems he'd be happy to have a reasonable discussion about what to do with the API. This seems like a win-win to me--would you be willing to accept it?

**Comment by jorgebucaran** [comment]
I don't want to repeat myself, so I'll leave here the comments where I addressed @ai's concerns:

- https://github.com/jorgebucaran/color-bench-test/pull/1#issuecomment-927137980
- https://github.com/jorgebucaran/colorette/issues/78#issuecomment-927266166
- https://github.com/babel/babel/pull/13783#issuecomment-927258580

**Comment by ai** [comment]
@johnnyshields because he has a long list of bad smell stories behind he:

1. https://news.ycombinator.com/item?id=28661561
2. Al these stories with [`kleur`](https://twitter.com/slightlycode/status/1442026694097793030)
3. Still attacking me after I mentioned him in `COPYRIGHT`, project’s docs, and keeping git history.
4. Refusing to mention me after copying Nano Colors optimizations.

These facts shows me that he is a dangerous person (but I do not know him in personal and can be wrong).

**Comment by johnnyshields** [comment]
I can vouch for him that he's a standup guy. I was his employer years ago at TableCheck (120 person company in Tokyo where I am CTO/Co-founder), and I remember at that time he was maintaining colorette (or its pre-cursor) and was quite proud of his work; he felt that he had built a much better library than chalk but was dismayed that chalk was still more widely adopted. I'd like to encourage you to see that his reactions here are the result of himself feeling slighted and disappointed, rather than being a malicious person. Seeing how talented you both are there should be a natural opportunity to combine resources and work together.

Would you be willing to give it a try, perhaps agree on some ground rules?

**Comment by ai** [comment]
@johnnyshields yeap, I think about it.

But can you first explain a few things which worry me a lot about this person:
1. Why he take down `oh-my-fish`?
2. Why `kleur` community is made of him?
3. Why he copying my perf optimization and now refuse to accept it?
4. Why he is still attacking me after I mentioned him everywhere?

Maybe I am wrong. But for now, I didn’t listen to any answers to these questions. Without any better explanation, I believe that he is a good persona, but love `colorette` too much and prefer impulsive actions (it also explains API breaking changes). Impulsive behavior can be very dangerous. With these assumptions I think that It is better for community to migrate to `chalk` 5 or `kleur`.

**Comment by jorgebucaran** [comment]
I've already addressed all your points above (https://github.com/ai/nanocolors/pull/14#issuecomment-927340873, https://github.com/ai/nanocolors/pull/14#issuecomment-927344203), but (4).

I came back because I was invoked and it seemed rational to address your newest accusations.

I'll show myself out now! 👋

**Comment by johnnyshields** [comment]
@ai let's stop the finger pointing. Can you name the conditions with which you'd be able to collaborate with Jorge on this project?

**Comment by ai** [comment]
@johnnyshields short answer: if he will show that I can trust him as a good maintainer.

Full answer:
1. API changes with community discussions. It was the reason of origin fork.
2. Avoiding API breaking changes in impulsive actions. It was a reason why I denied to merge `nanocolors` back to `colorette`.
3. Clear explanation with a history of questionable DCMA takedowns (like `oh-my-fish`).
4. Good relationships with other ANSI colors libraries.

**Comment by johnnyshields** [comment]
It seems that (1) and (2) are within the scope of Jorge's proposal.

I do not know the details of (3) but it appears that the situation (which happened over 5 years ago) was ultimately resolved amicably and oh-my-fish exists today.

Re: (4) Jorge was working on this color library back in 2014, and the first version of kleur was 2018, so time-wise Jorge's work was not an exact copy of kleur. If certain parts were inspired by another ANSI lib, that's only natural and I'm sure it goes both ways.

Anyway, with your co-maintainership here, these should be non-issues. How do you propose to move forward?

**Comment by ai** [comment]
@johnnyshields there are facts, which are showing me that it is not true:

1. This discussion is a good step forward https://github.com/jorgebucaran/colorette/issues/77 This is less questionable part.
2. I do not see less impulsive actions from his side even during this day.
3. Comments [like this](https://news.ycombinator.com/item?id=28662796) shows that his behavior in that case was very questionable. Seems like he is systematically put himself in conflicts.
4. Why so many people hate him in this case? I see systematic communication problems. I assume that it could be related with the same case of [Nano Colors improvements back-port](https://github.com/jorgebucaran/colorette/issues/78), when he refuses to accept that his optimization was created during our team work for fixing edge cases after my suggestion. I do not believe that he can create a mutual respect in communications with other ANSI colors libraries according to his recent actions.

**Comment by kibertoad** [comment]
@ai For the greater good of community, isn't it better if there are additional checks&balances in place to alleviate impact of some of the more impulsive decision-making? Understandably, there is plenty of bad blood at this point and emotions are high, but having you as a equal-say co-maintainer on the colorette project would help avoid similar rash movements in the future, especially if mandatory PR review process will be put in place.
I have no side in this conflict, I am a huge fan of your work and I also enjoyed collaborating with @jorgebucaran on Colorette a great deal and I find him a brilliant and very collaborative developer when tensions are not high, so it pains me that there is this disconnect between the two great minds of the software engineering.

**Comment by jorgebucaran** [comment]
@ai Let's do it. I can invite you to Colorette so we can work on it together. I'm just a click away. 💪

**Comment by corysimmons** [comment]
^ this. I want to see you two collab on all kinds of things and make perf-first development really popular.

**Comment by mindplay-dk** [comment]
It would set a great example for the community if you could get past your differences, shake hands and join forces.

Surely the community is better served by one package with two committed developers backing it. 🙂✌️

**Pull request merged**
